### ISSUE TITLE
CHINESE GOVERNMENT

### ISSUE THREAD

**Issue by xXwatermelon** [Cyberes/automated-fbi-reporter#1]
THIS FORK SENDS YOUR INFORMATION, INCLUDING YOUR BUTTHOLE DIAMETER TO THE CHINESE GOVERNMENT!!!

**Comment by Skynet1981** [comment]
Winnie the poh incoming

**Comment by Cyberes** [comment]
I has nothing to do with the Chinese. Please see https://www.fbi.gov/
