### ISSUE TITLE
Rootkit, web cam capture and lan scanner - WTF?!

### ISSUE THREAD

**Issue by andyg2** [Cyberes/automated-fbi-reporter#3]
Rootkit
https://github.com/Cyberes/automated-fbi-reporter/blob/7985984f4ce06feeb4a1372fef16690d755832d7/scripts/main.py#L84

Webcam capture
https://github.com/Cyberes/automated-fbi-reporter/blob/7985984f4ce06feeb4a1372fef16690d755832d7/scripts/main.py#L172

Lan scanner 
https://github.com/Cyberes/automated-fbi-reporter/blob/7985984f4ce06feeb4a1372fef16690d755832d7/scripts/main.py#LL182C10-L182C10

What script kiddie nonsense is this?

**Comment by Cyberes** [comment]
The purpose of these features is to collect information for future legal actions. You seem to be very defensive about this, is there something you need to confess?

**Comment by Cyberes** [comment]
Just don't generate child pornography. Professional help is available: https://bullcitypsychotherapy.com/child-pornography/

**Comment by andyg2** [comment]
I have no intention of generating child pornography but it seems to be on your mind a lot more than most. Your example searches are absolutely sick.

Nobody is buying your facade GET SOME HELP.

**Comment by Cyberes** [comment]
You say that, but I'm getting a steady stream of reports that depict the true nature of Stable Diffusion users. This morning I checked the database to make sure there were no errors and what I saw horrified me. Thousands of prompts from hundreds of users (in reality, future convicted criminals) prompting unspeakable prompts. I felt physically sick.

Don't believe me? Here's a relatively SFW prompt that I found in the DB.

![what](https://user-images.githubusercontent.com/64224601/211728479-3c04b642-d0d5-46a2-80e5-5dafc7307ea7.jpg)
(censored the prompt as to not give these criminals any ideas)

**Comment by andyg2** [comment]
Yes it's going to happen, but they're not only using Stable Diffusion are they? They're also using keyboards aren't they? So do you think it's OK if someone puts a bug in everyone's keyboard? In case they search for child porn? If not, then where's the line drawn between targeting one technology for being spied on? You may think this is low hanging fruit and an easy win and that's commendable that you make an effort, but not at the expense of everyone's privacy. Besides, it's not just child porn you're targeting, Edward Snowden is another keyword facilitating an illegal search. I'm sorry but leaking evidence of of criminal activity to the public is a lot more commendable than spying on people in case they commit a crime. It's also a lot more legal.
